# Generated by Django 5.0.4 on 2025-01-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiplom', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
