# Generated by Django 5.0.4 on 2025-01-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiplom', '0003_images_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='status',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
