# Generated by Django 5.0.4 on 2025-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiplom', '0004_images_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='lord',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
