# Generated by Django 5.0.4 on 2025-02-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiplom', '0006_images_image_prc_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_prc',
        ),
        migrations.AddField(
            model_name='images',
            name='prc_path',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
